export const create_request_selectors = {
    // Page Header
    heading_main: 'h4:has-text("Start with the waypoints")',
    heading_sub: 'h6:has-text("Fill in details about route")',
    
    // Navigation
    nav_logo: 'a[href="/request/list"] img',
    nav_requests: 'a[href="/request/list"]:has-text("Requests")',
    nav_transports: 'a[href="/transport/list"]:has-text("Transports")',
    nav_directory: 'a[href="/directory/list"]:has-text("Directory")',
    nav_reports: 'a[href="/reports"]:has-text("Reports")',
    nav_documents: 'a[href="/documents"]:has-text("Documents")',
    btn_user_menu: 'button:has-text("Vlado Kopecky Company")',
    tab_waypoints: 'button:has-text("1. Waypoints")',
    tab_cargo_info: 'button:has-text("2. Cargo info")',
    tab_carriers: 'button:has-text("3. Carriers")',
    tab_review: 'button:has-text("4. Review")',
    radio_one_way: 'input[type="radio"]:has-text("One way")',
    radio_round_trip: 'input[type="radio"]:has-text("Round trip")',
    btn_road: 'button:has-text("Road")',
    btn_air: 'button:has-text("Air")',
    btn_sea: 'button:has-text("Sea")',
    btn_rail: 'button:has-text("Rail")',
    btn_intermodal: 'button:has-text("Intermodal")',
    btn_waypoint1_remove: 'button:has-text("Remove")',
    radio_waypoint1_pickup: 'input[type="radio"]:has-text("Pickup point")',
    radio_waypoint1_delivery: 'input[type="radio"]:has-text("Delivery point")',
    input_waypoint1_earliest_pickup: 'input[aria-label="Earliest pickup time"]',
    input_waypoint1_latest_pickup: 'input[aria-label="Latest pickup time"]',
    input_waypoint1_name_company: 'input[placeholder="Name / Company"]',
    input_waypoint1_street: 'input[placeholder="Street and number"]',
    input_waypoint1_city: 'input[placeholder="City*"]',
    select_waypoint1_country: 'select[aria-label="Country*"]',
    input_waypoint1_zip: 'input[placeholder="ZIP"]',
    input_waypoint1_contact_name: 'input[placeholder="Contact name"]',
    input_waypoint1_email: 'input[placeholder="Email"]',
    input_waypoint1_phone: 'input[placeholder="Phone"]',
    chk_waypoint1_save_address: 'input[type="checkbox"]:has-text("Save address to directory")',
    input_waypoint1_reference: 'input[placeholder="Reference for pickup/delivery"]',
    chk_waypoint1_note: 'input[type="checkbox"]:has-text("Note")',
    btn_waypoint2_remove: 'button:has-text("Remove"):nth-of-type(2)',
    radio_waypoint2_pickup: 'input[type="radio"]:has-text("Pickup point"):nth-of-type(2)',
    radio_waypoint2_delivery: 'input[type="radio"]:has-text("Delivery point"):nth-of-type(2)',
    input_waypoint2_earliest_delivery: 'input[aria-label="Earliest delivery time"]',
    input_waypoint2_latest_delivery: 'input[aria-label="Latest delivery time"]',
    input_waypoint2_name_company: 'input[placeholder="Name / Company"]:nth-of-type(2)',
    input_waypoint2_street: 'input[placeholder="Street and number"]:nth-of-type(2)',
    input_waypoint2_city: 'input[placeholder="City*"]:nth-of-type(2)',
    select_waypoint2_country: 'select[aria-label="Country*"]:nth-of-type(2)',
    input_waypoint2_zip: 'input[placeholder="ZIP"]:nth-of-type(2)',
    input_waypoint2_contact_name: 'input[placeholder="Contact name"]:nth-of-type(2)',
    input_waypoint2_email: 'input[placeholder="Email"]:nth-of-type(2)',
    input_waypoint2_phone: 'input[placeholder="Phone"]:nth-of-type(2)',
    chk_waypoint2_save_address: 'input[type="checkbox"]:has-text("Save address to directory"):nth-of-type(2)',
    input_waypoint2_reference: 'input[placeholder="Reference for pickup/delivery"]:nth-of-type(2)',
    chk_waypoint2_note: 'input[type="checkbox"]:has-text("Note"):nth-of-type(2)',
    btn_add_waypoint: 'button:has-text("Add waypoint")',
    btn_reorder_waypoints: 'button:has-text("Reorder waypoints")',
    btn_check_route: 'button:has-text("Check route on map")',
    btn_continue: 'button:has-text("Continue")',
    text_copyright: ':text("© 2025 - 4Shipper by Transportly")',
    text_version: ':text("2025.18.0")',
    text_deployment: ':text("29.08.2025 09:07")',

    // Tab Content Headers
    heading_route_waypoints: 'h2:has-text("Route waypoints")',
    heading_define_waypoints: 'h6:has-text("Define route waypoint, pickup and delivery locations")',
    heading_waypoint1_date: 'h4:has-text("Date and time"):first-of-type',
    heading_waypoint1_address: 'h4:has-text("Address"):first-of-type',
    heading_waypoint2_date: 'h4:has-text("Date and time"):nth-of-type(2)',
    heading_waypoint2_address: 'h4:has-text("Address"):nth-of-type(2)',
    
    // Labels and Help Text
    label_transport_mode: ':text("Transportation mode")',
    label_earliest_pickup: ':text("Earliest pickup time*")',
    label_latest_pickup: ':text("Latest pickup time")',
    label_earliest_delivery: ':text("Earliest delivery time")',
    label_latest_delivery: ':text("Latest delivery time*")',
    label_name_company: ':text("Name / Company")',
    label_street: ':text("Street and number")',
    label_city: ':text("City*")',
    label_country: ':text("Country*")',
    label_zip: ':text("ZIP")',
    label_contact_name: ':text("Contact name")',
    label_email: ':text("Email")',
    label_phone: ':text("Phone")',
    text_reference_help: ':text("Reference will only be visible to the carrier who wins the request and confirms the transport from his side.")',
    
    // Form Section Labels
    section_waypoint1: '.waypoint-section:first-of-type',
    section_waypoint2: '.waypoint-section:nth-of-type(2)',
    section_transport_mode: '.transport-mode-section',
    section_route_details: '.route-details-section'
};
